name: k8s Status Check

on:
  schedule:
    - cron: '0 0 * * 0'  # RSM
  workflow_dispatch:

jobs:
  check_pods:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Connect to server and check cluster status
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: ${{ secrets.SERVER_PORT }}
          script: |
            echo "Checking Kubernetes nodes status"
            kubectl get nodes

            echo "Checking all pods in all namespaces"
            kubectl get pods --all-namespaces

            echo "Checking services in all namespaces"
            kubectl get services --all-namespaces

            echo "Checking deployments in all namespaces"
            kubectl get deployments --all-namespaces

            echo "Checking daemonsets in all namespaces"
            kubectl get daemonsets --all-namespaces

            echo "Checking statefulsets in all namespaces"
            kubectl get statefulsets --all-namespaces

            echo "Checking persistent volume claims in all namespaces"
            kubectl get pvc --all-namespaces

            echo "Checking persistent volumes"
            kubectl get pv

            echo "Checking events in all namespaces"
            kubectl get events --all-namespaces --sort-by='.metadata.creationTimestamp'

            echo "Checking configmaps in all namespaces"
            kubectl get configmaps --all-namespaces

            echo "Checking secrets in all namespaces"
            kubectl get secrets --all-namespaces

            echo "Checking cluster roles"
            kubectl get clusterroles

            echo "Checking cluster role bindings"
            kubectl get clusterrolebindings

            echo "Checking nodes resource usage"
            kubectl top nodes

            echo "Checking pods resource usage in all namespaces"
            kubectl top pods --all-namespaces
